-- Multitenant: cada peluquería es un registro de `negocio`; los datos se aíslan por negocio_id.
-- Los datos existentes pasan al negocio 1, con código 'demo'.

-- 1. negocio pasa a ser la tabla de tenants
ALTER TABLE negocio DROP CONSTRAINT negocio_id_check;
ALTER TABLE negocio ALTER COLUMN id DROP DEFAULT;
ALTER TABLE negocio ALTER COLUMN id TYPE BIGINT;
ALTER TABLE negocio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);
ALTER TABLE negocio ADD COLUMN codigo VARCHAR(40);
ALTER TABLE negocio ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE negocio ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();
UPDATE negocio SET codigo = 'demo' WHERE id = 1;
ALTER TABLE negocio ALTER COLUMN codigo SET NOT NULL;
ALTER TABLE negocio ADD CONSTRAINT uq_negocio_codigo UNIQUE (codigo);
ALTER TABLE negocio ADD CONSTRAINT ck_negocio_codigo CHECK (codigo ~ '^[a-z0-9-]{3,40}$');

-- 2. negocio_id en cada tabla de datos del negocio (venta_items se accede siempre por su venta)
DO $$
DECLARE t TEXT;
BEGIN
    FOREACH t IN ARRAY ARRAY['usuarios', 'categorias', 'servicios', 'productos', 'clientes', 'cajas', 'ventas'] LOOP
        EXECUTE format('ALTER TABLE %I ADD COLUMN negocio_id BIGINT NOT NULL DEFAULT 1 REFERENCES negocio (id)', t);
        EXECUTE format('ALTER TABLE %I ALTER COLUMN negocio_id DROP DEFAULT', t);
        EXECUTE format('CREATE INDEX idx_%s_negocio ON %I (negocio_id)', t, t);
    END LOOP;
END $$;

-- 3. Unicidad dentro de cada negocio (antes era global)
ALTER TABLE usuarios DROP CONSTRAINT usuarios_username_key;
CREATE UNIQUE INDEX uq_usuarios_negocio_username ON usuarios (negocio_id, lower(username));

ALTER TABLE categorias DROP CONSTRAINT categorias_nombre_key;
ALTER TABLE categorias ADD CONSTRAINT uq_categorias_negocio_nombre UNIQUE (negocio_id, nombre);

ALTER TABLE productos DROP CONSTRAINT productos_sku_key;
ALTER TABLE productos ADD CONSTRAINT uq_productos_negocio_sku UNIQUE (negocio_id, sku);

-- Una caja abierta por negocio
DROP INDEX uq_caja_abierta;
CREATE UNIQUE INDEX uq_caja_abierta ON cajas (negocio_id) WHERE estado = 'ABIERTA';

-- Reportes filtran por negocio y rango de fechas
DROP INDEX idx_ventas_fecha;
CREATE INDEX idx_ventas_negocio_fecha ON ventas (negocio_id, fecha);

-- 4. Usuarios de la plataforma (dan de alta y suspenden negocios; no operan dentro de ellos)
CREATE TABLE superadmins (
    id             BIGSERIAL PRIMARY KEY,
    nombre         VARCHAR(120) NOT NULL,
    username       VARCHAR(50)  NOT NULL UNIQUE,
    password_hash  VARCHAR(100) NOT NULL,
    activo         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
